# Imagem Debian10 com ssh e python3
# Password para root foi definida como 123456

# Imagem usada para criar containers representando targets para teste com ansible.
# Voce criar quantos containers desejar e executa seus playbooks contra os mesmos.

FROM debian:10

RUN apt-get update && apt-get install -y openssh-server
RUN apt-get install -y python3
RUN mkdir /var/run/sshd
RUN echo 'root:123456' | chpasswd
RUN sed -i 's/#*PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

CMD ["/usr/sbin/sshd", "-D"]

# comando para gerar a imagem com este Dockerfile. A imagem se chamara debianssh
# docker build -t debianssh .

# comando para criar um novo container baseado nesta imagem. O nome é opcional.
#docker run -d [--name <nome_qualquer>] debianssh
